variables:
  NUGET_VERSION: 0.1

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'build-scripts/**'

jobs:

- job: Repack
  pool:
    vmImage: 'ubuntu-20.04'
  timeoutInMinutes: 150

  steps:
  - bash: |
       cd build-scripts
       bash Repack-Postgres-on-Linux.sh
    condition: succeededOrFailed()
    displayName: 'Lets do it'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'

  - bash: Show-System-Stat
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Linux System Statistic'
